# Spark DataFrames Project Exercise

Let's get some quick practice with your new Spark DataFrame skills, you will be asked some basic questions about some stock market data, in this case Walmart Stock from the years 2012-2017. This exercise will just ask a bunch of questions, unlike the future machine learning exercises, which will be a little looser and be in the form of "Consulting Projects", but more on that later!

For now, just answer the questions and complete the tasks below.

#### Use the walmart_stock.csv file to Answer and complete the  tasks below!

#### Start a simple Spark Session

In [2]:
from pyspark.sql import SparkSession

#### Load the Walmart Stock CSV File, have Spark infer the data types.

In [4]:
spark = SparkSession.builder.appName('Walmart').getOrCreate()
df = spark.read.csv('walmart_stock.csv', header=True, inferSchema=True)

In [5]:
df.show()

+-------------------+------------------+------------------+------------------+------------------+--------+------------------+
|               Date|              Open|              High|               Low|             Close|  Volume|         Adj Close|
+-------------------+------------------+------------------+------------------+------------------+--------+------------------+
|2012-01-03 00:00:00|         59.970001|         61.060001|         59.869999|         60.330002|12668800|52.619234999999996|
|2012-01-04 00:00:00|60.209998999999996|         60.349998|         59.470001|59.709998999999996| 9593300|         52.078475|
|2012-01-05 00:00:00|         59.349998|         59.619999|         58.369999|         59.419998|12768200|         51.825539|
|2012-01-06 00:00:00|         59.419998|         59.450001|         58.869999|              59.0| 8069400|          51.45922|
|2012-01-09 00:00:00|         59.029999|         59.549999|         58.919998|             59.18| 6679300|51.616215000000004|
|2012-01-10 00:00:00|             59.43|59.709998999999996|             58.98|59.040001000000004| 6907300|         51.494109|
|2012-01-11 00:00:00|         59.060001|         59.529999|59.040001000000004|         59.400002| 6365600|         51.808098|
|2012-01-12 00:00:00|59.790001000000004|              60.0|         59.400002|              59.5| 7236400|51.895315999999994|
|2012-01-13 00:00:00|             59.18|59.610001000000004|59.009997999999996|59.540001000000004| 7729300|51.930203999999996|
|2012-01-17 00:00:00|         59.869999|60.110001000000004|             59.52|         59.849998| 8500000|         52.200581|
|2012-01-18 00:00:00|59.790001000000004|         60.029999|         59.650002|60.009997999999996| 5911400|         52.340131|
|2012-01-19 00:00:00|             59.93|             60.73|             59.75|60.610001000000004| 9234600|         52.863447|
|2012-01-20 00:00:00|             60.75|             61.25|         60.669998|61.009997999999996|10378800|53.212320999999996|
|2012-01-23 00:00:00|         60.810001|             60.98|60.509997999999996|             60.91| 7134100|         53.125104|
|2012-01-24 00:00:00|             60.75|              62.0|             60.75|61.389998999999996| 7362800| 53.54375400000001|
|2012-01-25 00:00:00|             61.18|61.610001000000004|61.040001000000004|         61.470001| 5915800| 53.61353100000001|
|2012-01-26 00:00:00|         61.799999|             61.84|             60.77|         60.970001| 7436200|         53.177436|
|2012-01-27 00:00:00|60.860001000000004|         61.119999|60.540001000000004|60.709998999999996| 6287300|         52.950665|
|2012-01-30 00:00:00|         60.470001|             61.32|         60.349998|         61.299999| 7636900|53.465256999999994|
|2012-01-31 00:00:00|         61.529999|             61.57|         60.580002|61.360001000000004| 9761500|53.517590000000006|
+-------------------+------------------+------------------+------------------+------------------+--------+------------------+
only showing top 20 rows

#### What are the column names?

In [6]:
df.columns

['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close']

#### What does the Schema look like?

In [9]:
df.printSchema()

root
 |-- Date: timestamp (nullable = true)
 |-- Open: double (nullable = true)
 |-- High: double (nullable = true)
 |-- Low: double (nullable = true)
 |-- Close: double (nullable = true)
 |-- Volume: integer (nullable = true)
 |-- Adj Close: double (nullable = true)

#### Print out the first 5 columns.

In [11]:
df.head(5)

[Row(Date=datetime.datetime(2012, 1, 3, 0, 0), Open=59.970001, High=61.060001, Low=59.869999, Close=60.330002, Volume=12668800, Adj Close=52.619234999999996),
 Row(Date=datetime.datetime(2012, 1, 4, 0, 0), Open=60.209998999999996, High=60.349998, Low=59.470001, Close=59.709998999999996, Volume=9593300, Adj Close=52.078475),
 Row(Date=datetime.datetime(2012, 1, 5, 0, 0), Open=59.349998, High=59.619999, Low=58.369999, Close=59.419998, Volume=12768200, Adj Close=51.825539),
 Row(Date=datetime.datetime(2012, 1, 6, 0, 0), Open=59.419998, High=59.450001, Low=58.869999, Close=59.0, Volume=8069400, Adj Close=51.45922),
 Row(Date=datetime.datetime(2012, 1, 9, 0, 0), Open=59.029999, High=59.549999, Low=58.919998, Close=59.18, Volume=6679300, Adj Close=51.616215000000004)]

#### Use describe() to learn about the DataFrame.

In [14]:
df.describe().show()

+-------+------------------+-----------------+-----------------+-----------------+-----------------+-----------------+
|summary|              Open|             High|              Low|            Close|           Volume|        Adj Close|
+-------+------------------+-----------------+-----------------+-----------------+-----------------+-----------------+
|  count|              1258|             1258|             1258|             1258|             1258|             1258|
|   mean| 72.35785375357709|72.83938807631165| 71.9186009594594|72.38844998012726|8222093.481717011|67.23883848728146|
| stddev|  6.76809024470826|6.768186808159218|6.744075756255496|6.756859163732991|  4519780.8431556|6.722609449996857|
|    min|56.389998999999996|        57.060001|        56.299999|        56.419998|          2094900|        50.363689|
|    max|         90.800003|        90.970001|            89.25|        90.470001|         80898100|84.91421600000001|
+-------+------------------+-----------------+-----------------+-----------------+-----------------+-----------------+

## Bonus Question!
#### There are too many decimal places for mean and stddev in the describe() dataframe. Format the numbers to just show up to two decimal places. Pay careful attention to the datatypes that .describe() returns, we didn't cover how to do this exact formatting, but we covered something very similar. [Check this link for a hint](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.Column.cast)

If you get stuck on this, don't worry, just view the solutions.

In [59]:
# cast datatype
type(df.select(df.Open.cast("string")).collect()[1][0]) #string
type(df.select(df.Open.cast("int")).collect()[1][0]) #integer

str

In [77]:
df.describe().printSchema()

root
 |-- summary: string (nullable = true)
 |-- Open: string (nullable = true)
 |-- High: string (nullable = true)
 |-- Low: string (nullable = true)
 |-- Close: string (nullable = true)
 |-- Volume: string (nullable = true)
 |-- Adj Close: string (nullable = true)

In [123]:
from pyspark.sql.functions import format_number
# columns ['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close']
# columns = df.columns.remove('Date')
columns = df.columns
columns.remove('Date')

['Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close']

In [125]:
for col in columns:
    df.select(df[col].cast("int"))
    print(col, type(col))

Open <class 'str'>
High <class 'str'>
Low <class 'str'>
Close <class 'str'>
Volume <class 'str'>
Adj Close <class 'str'>

In [94]:
df.select(format_number((df["High"].cast("float")),2)).collect()

[Row(format_number(CAST(High AS FLOAT), 2)='61.06'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.35'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.62'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.45'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.55'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.71'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.53'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.00'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.61'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.11'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.03'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.73'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.25'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.98'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.00'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.61'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.84'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.12'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.32'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.57'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.63'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.47'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.43'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.98'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.90'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.02'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.16'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.91'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.08'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.24'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.44'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.19'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.57'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.50'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.90'),
 Row(format_number(CAST(High AS FLOAT), 2)='58.90'),
 Row(format_number(CAST(High AS FLOAT), 2)='58.95'),
 Row(format_number(CAST(High AS FLOAT), 2)='58.78'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.10'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.33'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.42'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.28'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.59'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.22'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.86'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.95'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.20'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.90'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.08'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.15'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.26'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.47'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.88'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.86'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.72'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.77'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.85'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.32'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.50'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.48'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.95'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.42'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.49'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.41'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.59'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.69'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.34'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.39'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.29'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.20'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.21'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.81'),
 Row(format_number(CAST(High AS FLOAT), 2)='61.95'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.25'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.05'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.49'),
 Row(format_number(CAST(High AS FLOAT), 2)='60.24'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.35'),
 Row(format_number(CAST(High AS FLOAT), 2)='58.43'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.43'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.46'),
 Row(format_number(CAST(High AS FLOAT), 2)='58.99'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.27'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.32'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.20'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.18'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.36'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.37'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.24'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.61'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.65'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.55'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.65'),
 Row(format_number(CAST(High AS FLOAT), 2)='59.66'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.50'),
 Row(format_number(CAST(High AS FLOAT), 2)='62.63'),
 Row(format_number(CAST(High AS FLOAT), 2)='63.10'),
 Row(format_number(CAST(High AS FLOAT), 2)='63.95'),
 Row(format_number(CAST(High AS FLOAT), 2)='64.69'),
 Row(format_number(CAST(High AS FLOAT), 2)='65.18'),
 Row(format_number(CAST(High AS FLOAT), 2)='65.50'),
 Row(format_number(CAST(High AS FLOAT), 2)='65.76'),
 Row(format_number(CAST(High AS FLOAT), 2)='65.95'),
 Row(format_number(CAST(High AS FLOAT), 2)='66.66'),
 Row(format_number(CAST(High AS FLOAT), 2)='65.88'),
 Row(format_number(CAST(High AS FLOAT), 2)='66.13'),
 Row(format_number(CAST(High AS FLOAT), 2)='65.90'),
 Row(format_number(CAST(High AS FLOAT), 2)='65.97'),
 Row(format_number(CAST(High AS FLOAT), 2)='66.08'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.23'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.48'),
 Row(format_number(CAST(High AS FLOAT), 2)='67.85'),
 Row(format_number(CAST(High AS FLOAT), 2)='67.75'),
 Row(format_number(CAST(High AS FLOAT), 2)='67.79'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.06'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.28'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.25'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.54'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.66'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.35'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.23'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.92'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.75'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.35'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.72'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.95'),
 Row(format_number(CAST(High AS FLOAT), 2)='70.77'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.30'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.36'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.76'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.58'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.44'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.62'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.24'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.18'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.10'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.46'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.86'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.49'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.99'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.24'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.46'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.95'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.80'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.24'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.98'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.79'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.16'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.96'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.92'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.60'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.51'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.52'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.25'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.69'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.27'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.52'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.75'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.69'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.41'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.34'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.85'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.94'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.20'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.79'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.71'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.02'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.75'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.95'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.84'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.95'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.81'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.80'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.12'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.42'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.35'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.19'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.99'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.68'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.17'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.63'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.82'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.09'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.96'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.05'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.84'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.50'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.06'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.49'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.36'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.75'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.01'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.50'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.55'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.38'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.81'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.61'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.04'),
 Row(format_number(CAST(High AS FLOAT), 2)='77.35'),
 Row(format_number(CAST(High AS FLOAT), 2)='77.60'),
 Row(format_number(CAST(High AS FLOAT), 2)='77.50'),
 Row(format_number(CAST(High AS FLOAT), 2)='77.23'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.71'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.78'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.49'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.00'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.50'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.42'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.68'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.16'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.57'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.20'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.28'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.90'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.98'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.60'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.60'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.30'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.00'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.69'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.69'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.13'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.24'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.06'),
 Row(format_number(CAST(High AS FLOAT), 2)='70.24'),
 Row(format_number(CAST(High AS FLOAT), 2)='70.23'),
 Row(format_number(CAST(High AS FLOAT), 2)='70.17'),
 Row(format_number(CAST(High AS FLOAT), 2)='70.81'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.04'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.12'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.34'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.60'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.02'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.85'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.59'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.34'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.70'),
 Row(format_number(CAST(High AS FLOAT), 2)='70.35'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.36'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.30'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.51'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.66'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.50'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.06'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.16'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.81'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.65'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.42'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.35'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.30'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.24'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.35'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.18'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.92'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.89'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.71'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.03'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.79'),
 Row(format_number(CAST(High AS FLOAT), 2)='68.67'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.24'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.37'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.32'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.20'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.65'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.64'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.99'),
 Row(format_number(CAST(High AS FLOAT), 2)='70.00'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.50'),
 Row(format_number(CAST(High AS FLOAT), 2)='70.20'),
 Row(format_number(CAST(High AS FLOAT), 2)='70.12'),
 Row(format_number(CAST(High AS FLOAT), 2)='70.44'),
 Row(format_number(CAST(High AS FLOAT), 2)='70.54'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.90'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.07'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.32'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.64'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.64'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.51'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.66'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.70'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.23'),
 Row(format_number(CAST(High AS FLOAT), 2)='70.00'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.45'),
 Row(format_number(CAST(High AS FLOAT), 2)='69.85'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.47'),
 Row(format_number(CAST(High AS FLOAT), 2)='70.54'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.34'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.39'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.96'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.88'),
 Row(format_number(CAST(High AS FLOAT), 2)='71.90'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.26'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.04'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.13'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.61'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.39'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.24'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.90'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.20'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.00'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.50'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.73'),
 Row(format_number(CAST(High AS FLOAT), 2)='72.87'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.38'),
 Row(format_number(CAST(High AS FLOAT), 2)='73.47'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.29'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.11'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.09'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.96'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.97'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.93'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.05'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.68'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.58'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.41'),
 Row(format_number(CAST(High AS FLOAT), 2)='77.45'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.46'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.38'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.37'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.85'),
 Row(format_number(CAST(High AS FLOAT), 2)='79.28'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.86'),
 Row(format_number(CAST(High AS FLOAT), 2)='79.07'),
 Row(format_number(CAST(High AS FLOAT), 2)='79.05'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.44'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.44'),
 Row(format_number(CAST(High AS FLOAT), 2)='79.22'),
 Row(format_number(CAST(High AS FLOAT), 2)='79.50'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.83'),
 Row(format_number(CAST(High AS FLOAT), 2)='79.15'),
 Row(format_number(CAST(High AS FLOAT), 2)='79.25'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.30'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.66'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.49'),
 Row(format_number(CAST(High AS FLOAT), 2)='79.34'),
 Row(format_number(CAST(High AS FLOAT), 2)='79.16'),
 Row(format_number(CAST(High AS FLOAT), 2)='79.14'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.66'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.96'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.91'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.94'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.86'),
 Row(format_number(CAST(High AS FLOAT), 2)='79.96'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.86'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.59'),
 Row(format_number(CAST(High AS FLOAT), 2)='77.90'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.18'),
 Row(format_number(CAST(High AS FLOAT), 2)='77.80'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.94'),
 Row(format_number(CAST(High AS FLOAT), 2)='77.41'),
 Row(format_number(CAST(High AS FLOAT), 2)='78.04'),
 Row(format_number(CAST(High AS FLOAT), 2)='77.05'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.54'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.63'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.80'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.38'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.95'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.74'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.87'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.65'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.83'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.71'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.33'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.27'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.45'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.88'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.96'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.66'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.20'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.79'),
 Row(format_number(CAST(High AS FLOAT), 2)='74.75'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.18'),
 Row(format_number(CAST(High AS FLOAT), 2)='76.11'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.66'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.28'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.68'),
 Row(format_number(CAST(High AS FLOAT), 2)='75.12'),

#### Create a new dataframe with a column called HV Ratio that is the ratio of the High Price versus volume of stock traded for a day.

+--------------------+
|            HV Ratio|
+--------------------+
|4.819714653321546E-6|
|6.290848613094555E-6|
|4.669412994783916E-6|
|7.367338463826307E-6|
|8.915604778943901E-6|
|8.644477436914568E-6|
|9.351828421515645E-6|
| 8.29141562102703E-6|
|7.712212102001476E-6|
|7.071764823529412E-6|
|1.015495466386981E-5|
|6.576354146362592...|
| 5.90145296180676E-6|
|8.547679455011844E-6|
|8.420709512685392E-6|
|1.041448341728929...|
|8.316075414862431E-6|
|9.721183814992126E-6|
|8.029436027707578E-6|
|6.307432259386365E-6|
+--------------------+
only showing top 20 rows

#### What day had the Peak High in Price?

datetime.datetime(2015, 1, 13, 0, 0)

#### What is the mean of the Close column?

+-----------------+
|       avg(Close)|
+-----------------+
|72.38844998012726|
+-----------------+

#### What is the max and min of the Volume column?

+-----------+-----------+
|max(Volume)|min(Volume)|
+-----------+-----------+
|   80898100|    2094900|
+-----------+-----------+

#### How many days was the Close lower than 60 dollars?

81

#### What percentage of the time was the High greater than 80 dollars ?
#### In other words, (Number of Days High>80)/(Total Days in the dataset)

9.141494435612083

#### What is the Pearson correlation between High and Volume?
#### [Hint](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.DataFrameStatFunctions.corr)

+-------------------+
| corr(High, Volume)|
+-------------------+
|-0.3384326061737161|
+-------------------+

#### What is the max High per year?

+----+---------+
|Year|max(High)|
+----+---------+
|2015|90.970001|
|2013|81.370003|
|2014|88.089996|
|2012|77.599998|
|2016|75.190002|
+----+---------+

#### What is the average Close for each Calendar Month?
#### In other words, across all the years, what is the average Close price for Jan,Feb, Mar, etc... Your result will have a value for each of these months.

+-----+-----------------+
|Month|       avg(Close)|
+-----+-----------------+
|    1|71.44801958415842|
|    2|  71.306804443299|
|    3|71.77794377570092|
|    4|72.97361900952382|
|    5|72.30971688679247|
|    6| 72.4953774245283|
|    7|74.43971943925233|
|    8|73.02981855454546|
|    9|72.18411785294116|
|   10|71.57854545454543|
|   11| 72.1110893069307|
|   12|72.84792478301885|
+-----+-----------------+

# Great Job!